### DISCUSSION TITLE
Define version 2 for toml configuration file

### DISCUSSION THREAD

**Discussion by josecelano** [torrust/torrust-tracker#853] [Proposals]
Relates to: 
- https://github.com/torrust/torrust-tracker/issues/401
- https://github.com/torrust/torrust-index/issues/591

The final [configuration overhaul](https://github.com/torrust/torrust-tracker/issues/401) step would be defining a new config file structure.

An extra validation could be needed like the one described [here](https://github.com/torrust/torrust-tracker/pull/790). For example, if  you enable TSL for the tracker API you must provide both the certificate path and the certificate key path:

```toml
[http_api]
bind_address = "127.0.0.1:1212"
enabled = true
ssl_cert_path = ""
ssl_enabled = false
ssl_key_path = ""
```

I think that type of validation could be implemented after parsing the injected configuration or maybe just by reorganising the toml file structure. For example:

No API enabled:

```toml
# No section [http_api]
```

API enabled but no TSL enabled:

```toml
[http_api]
bind_address = "127.0.0.1:1212"
```

API enabled with TSL enabled:

```toml
[http_api]
bind_address = "127.0.0.1:1212"

[http_api.tsl_config]
ssl_cert_path = "./storage/tracker/lib/tls/localhost.crt"
ssl_key_path = "./storage/tracker/lib/tls/localhost.key"
```

We would not need the `enabled` field. If the section is present the feature is enabled. If it's not it means that feature is disabled.

These breaking changes will be added in a new `v2` configuration in a new PR.

I would like to discuss the final version 2 for the config file before implementing it.

### Current Configuration

```toml
log_level = "info"
mode = "public"
db_driver = "Sqlite3"
db_path = "./storage/tracker/lib/database/sqlite3.db"
announce_interval = 120
min_announce_interval = 120
on_reverse_proxy = false
external_ip = "0.0.0.0"
tracker_usage_statistics = true
persistent_torrent_completed_stat = false
max_peer_timeout = 900
inactive_peer_cleanup_interval = 600
remove_peerless_torrents = true

[[udp_trackers]]
enabled = false
bind_address = "0.0.0.0:6969"

[[http_trackers]]
enabled = false
bind_address = "0.0.0.0:7070"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api]
enabled = true
bind_address = "127.0.0.1:1212"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api.access_tokens]
admin = "MyAccessToken"

[health_check_api]
bind_address = "127.0.0.1:1313"
```

**Comment by josecelano** [comment]
### Proposal 1

The example contains:

- One UDP tracker
- Two HTTP trackers: the first one without TSL configuration.

`enabled` booleans have been removed. If the config option is present, then it's enabled. There is no configuration for "disabled" services. You just remove that configuration. You have to restart the service anyway.

**TOML:**

```toml
[core]

mode = "public"
log_level = "info"

# BitTorrent protocols
announce_interval = 120
min_announce_interval = 120

# database
db_driver = "Sqlite3"
db_path = "./storage/tracker/lib/database/sqlite3.db"

# network
on_reverse_proxy = false
external_ip = "0.0.0.0"

# torrents cleanup job
inactive_peer_cleanup_interval = 600
max_peer_timeout = 900
remove_peerless_torrents = true

# persistence
persistent_torrent_completed_stat = false

# feature flags
tracker_usage_statistics = true

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[[http_trackers]]
bind_address = "0.0.0.0:7071"

[[http_trackers.tsl_config]]
ssl_cert_path = ""
ssl_key_path = ""

[http_api]
bind_address = "127.0.0.1:1212"

[http_api.tsl_config]
ssl_cert_path = "./storage/tracker/lib/tls/localhost.crt"
ssl_key_path = "./storage/tracker/lib/tls/localhost.key"

[http_api.access_tokens]
admin = "MyAccessToken"

[health_check_api]
bind_address = "127.0.0.1:1313"
```

**JSON:**

```json
{
  "core": {
    "mode": "public",
    "log_level": "info",
    "announce_interval": 120,
    "min_announce_interval": 120,
    "db_driver": "Sqlite3",
    "db_path": "./storage/tracker/lib/database/sqlite3.db",
    "on_reverse_proxy": false,
    "external_ip": "0.0.0.0",
    "inactive_peer_cleanup_interval": 600,
    "max_peer_timeout": 900,
    "remove_peerless_torrents": true,
    "persistent_torrent_completed_stat": false,
    "tracker_usage_statistics": true
  },
  "udp_trackers": [
    {
      "bind_address": "0.0.0.0:6969"
    }
  ],
  "http_trackers": [
    {
      "bind_address": "0.0.0.0:7070"
    },
    {
      "bind_address": "0.0.0.0:7071",
      "tsl_config": [
        {
          "ssl_cert_path": "./storage/tracker/lib/tls/localhost.crt",
          "ssl_key_path": "./storage/tracker/lib/tls/localhost.key"
        }
      ]
    }
  ],
  "http_api": {
    "bind_address": "127.0.0.1:1212",
    "tsl_config": {
      "ssl_cert_path": "",
      "ssl_key_path": ""
    },
    "access_tokens": {
      "admin": "MyAccessToken"
    }
  },
  "health_check_api": {
    "bind_address": "127.0.0.1:1313"
  }
}
```

Commented subsections in the `core` section could also be tables (dictionaries).

cc @da2ce7
