### ISSUE TITLE
Missing packages in deployment workflow

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1010]
The workflow step to publish the crates doesn't include all of them. The missing ones:

- `torrust-tracker-clock`
- `torrust-tracker-torrent-repository`

```yml
  publish:
    name: Publish
    environment: deployment
    needs: test
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: setup
        name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - id: publish
        name: Publish Crates
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.TORRUST_UPDATE_CARGO_REGISTRY_TOKEN }}"
        run: |
          cargo publish -p torrust-tracker-contrib-bencode
          cargo publish -p torrust-tracker-located-error
          cargo publish -p torrust-tracker-primitives
          cargo publish -p torrust-tracker-configuration
          cargo publish -p torrust-tracker-test-helpers
          cargo publish -p torrust-tracker
```
