### ISSUE TITLE
Version 3.0.0 of all packages were not published because the workflow fails

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1057]
https://github.com/torrust/torrust-tracker/actions/runs/11144837601

![image](https://github.com/user-attachments/assets/939e229f-2e85-4190-92fb-f68766c42f45)

**Comment by josecelano** [comment]
There is a missing strategy in the `publish` job:

```
strategy:
  matrix:
    toolchain: [nightly, stable]
```

We should use `stable` as @da2ce7 pointed out:

```
  publish:
    name: Publish
    environment: deployment
    needs: test
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: setup
        name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - id: publish
        name: Publish Crates
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.TORRUST_UPDATE_CARGO_REGISTRY_TOKEN }}"
        run: |
          cargo publish -p torrust-tracker-contrib-bencode
          cargo publish -p torrust-tracker-located-error
          cargo publish -p torrust-tracker-primitives
          cargo publish -p torrust-tracker-clock
          cargo publish -p torrust-tracker-configuration
          cargo publish -p torrust-tracker-torrent-repository
          cargo publish -p torrust-tracker-test-helpers
          cargo publish -p torrust-tracker
```
