### ISSUE TITLE
Test compilation in different OSs

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1099]
Relates to: https://github.com/torrust/torrust-tracker/issues/325

We could create a new workflow only for that or change the `testing` workflow,

From:

```yaml
  unit:
    name: Units
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        toolchain: [nightly, stable]
```

To:

```yaml
  unit:
    name: Units on ${{ matrix.os }} with toolchain ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [nightly, stable]
```

It may be too slow to run all tests in all OSs. We can also add a new job only for building and test compilation, not test execution.

I have to check if it compiles in macOS. Apparently, it's fixed in [Windows](https://github.com/torrust/torrust-tracker/pull/1098).

cc @da2ce7
