### ISSUE TITLE
Consider config option to ignore connection ID expiration in UDP tracker

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1136]
Relates to:
 - https://github.com/chihaya/chihaya/issues/417
 - https://github.com/torrust/torrust-demo/issues/14
 - https://github.com/torrust/torrust-tracker/issues/1096

We have recently implemented an IP ban service to ban IPs that are not sending the correct connection ID for the UDP tracker.

Initially, we thought it was a DDoS attack or spam, but it seems to be a [common problem](https://github.com/chihaya/chihaya/issues/417). It seems there are some [BitTorrent clients](https://github.com/chihaya/chihaya/issues/417) that do not implement the [UDP specification](https://www.bittorrent.org/beps/bep_0015.html) correctly.

![image](https://github.com/user-attachments/assets/7a1ffd1c-e969-4b6c-96d6-4f78a4d063ec)

[Some people have reported bad clients even increasing the expiration for the connection ID to 2 hours](https://github.com/chihaya/chihaya/issues/417). That probably means some clients don't care at all about the connection ID, presumably because some trackers don't care either.

We could add a configuration option to increase that limit, but I would prefer to strcitly follow the specification.

cc @da2ce7

**Comment by josecelano** [comment]
I did not remember (because it was added by @da2ce7)  there is already a configuration option to increase the lifetime of the cookie:

```toml
[[udp_trackers]]
bind_address = "0.0.0.0:6969"

  [udp_trackers.cookie_lifetime]
  secs = 120
  nanos = 0
```

@da2ce7 suggested to add a flag to ignore connection ID on the [weekly meeting](https://github.com/orgs/nautilus-cyberneering/discussions/127).

```toml
[[udp_trackers]]
bind_address = "0.0.0.0:6969"
connection_id_validation_enabled = true # deafults to `true`

  [udp_trackers.cookie_lifetime]
  secs = 120
  nanos = 0
```
