### ISSUE TITLE
Overhaul stats: Start collecting stats per server instance (per socket)

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1403]
### Option 1: With independent event sender and stats repositories per server instance

IMPORTANT: This  option has been discarded.

When the `tracker_usage_statistics` is enabled in the HTTP or UDP server config the application should create an independent event sender and metrics repository for that server.

```toml
[[udp_trackers]]
bind_address = "0.0.0.0:6969"
tracker_usage_statistics = true 

[[http_trackers]]
bind_address = "0.0.0.0:7070"
tracker_usage_statistics = true
```

I will implement it by using the option 2 described [here](https://github.com/torrust/torrust-tracker/issues/1263#issuecomment-2741256154).

### Option 2. Segregated metrics within the current global stats repositories

More info about this option [here](https://github.com/torrust/torrust-tracker/issues/1263#issuecomment-2748955164).

### NOTES

In this issue:

 - I will not expose the new metrics via the public REST API yet.
 - Metrics are still the same (same metrics and same names as the global metrics).
