### ISSUE TITLE
Docker Security Overhaul: Implement Image Signing

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1461]
We should sign the docker images. We can use [cosign](https://github.com/sigstore/cosign).

I've added a guide created with an AI model. It hasn't been tested yet.

AI model: [R1 Distill Qwen 32B | DeepInfra](https://openrouter.ai/deepseek/deepseek-r1-distill-qwen-32b)

Response:

---

**Step-by-Step Guide: Integrating Image Signing with Cosign in a GitHub Workflow**

1. **Generate Cosign Key Pair**

   - **Command:** Run the following command in your terminal to generate a Cosign key pair:

     ```bash
     cosign generate-key-pair --output cosign-key/
     ```

   - **Result:** This creates two files:
     - `cosign-key/cosign.key` (private key)
     - `cosign-key/cosign.pub` (public key)

2. **Store Private Key as a GitHub Secret**

   - **Navigate to Repository Settings:**
     - Open your GitHub repository.
     - Click on **Settings**.
     - Under **Repository secrets**, select **Actions**.

   - **Add New Secret:**
     - Click **Add secret**.
     - **Name:** `DOCKER_REPO_PRIVATE_KEY`
     - **Value:** Paste the contents of `cosign-key/cosign.key`.
     - Click **Add secret**.

3. **Update GitHub Workflow File**

   - **File to Modify:** The workflow file (`github/workflows/Container.yml`) needs to be updated.

   - **Add Cosign Action:**
     - Include the `cosign/action-cosign` action under the `actions` section if not already present.

   - **Modify the `publish_development` Job:**

     After the image is built and before pushing, add the signing step:

     ```yaml
     - name: Sign Docker Image
       uses: cosign/action-cosign@v2
       with:
         key: ${{ secrets.DOCKER_REPO_PRIVATE_KEY }}
         image: ${{ steps.meta.outputs.tags }}
         CosignArguments: sign
     ```

   - **Modify the `publish_release` Job:**

     Similarly, add the signing step after building the image:

     ```yaml
     - name: Sign Docker Image
       uses: cosign/action-cosign@v2
       with:
         key: ${{ secrets.DOCKER_REPO_PRIVATE_KEY }}
         image: ${{ steps.meta.outputs.tags }}
         CosignArguments: sign
     ```

4. **Update the Complete Workflow**

   The updated workflow file should resemble the following, incorporating the Cosign action into both publication jobs:

   ```yaml
   name: Container

   on:
     push:
       branches:
         - "develop"
         - "main"
         - "releases/**/*"
     pull_request:
       branches:
         - "develop"
         - "main"

   env:
     CARGO_TERM_COLOR: always

   jobs:
     test:
       name: Test (Docker)
       runs-on: ubuntu-latest

       strategy:
         matrix:
           target: [debug, release]

       steps:
         - id: setup
           name: Setup Toolchain
           uses: docker/setup-buildx-action@v3

         - id: build
           name: Build
           uses: docker/build-push-action@v6
           with:
             file: ./Containerfile
             push: false
             load: true
             target: ${{ matrix.target }}
             tags: torrust-tracker:local
             cache-from: type=gha
             cache-to: type=gha

         - id: inspect
           name: Inspect
           run: docker image inspect torrust-tracker:local

         - id: checkout
           name: Checkout Repository
           uses: actions/checkout@v4

         - id: compose
           name: Compose
           run: docker compose build

     context:
       name: Context
       needs: test
       runs-on: ubuntu-latest

       outputs:
         continue: ${{ steps.check.outputs.continue }}
         type: ${{ steps.check.outputs.type }}
         version: ${{ steps.check.outputs.version }}

       steps:
         - id: check
           name: Check Context
           run: |
             if [[ "${{ github.repository }}" == "torrust/torrust-tracker" ]]; then
               if [[ "${{ github.event_name }}" == "push" ]]; then
                 if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then

                   echo "type=development" >> $GITHUB_OUTPUT
                   echo "continue=true" >> $GITHUB_OUTPUT
                   echo "On \`main\` Branch, Type: \`development\`"

                 elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then

                   echo "type=development" >> $GITHUB_OUTPUT
                   echo "continue=true" >> $GITHUB_OUTPUT
                   echo "On \`develop\` Branch, Type: \`development\`"

                 elif [[ $(echo "${{ github.ref }}" | grep -P '^(refs\/heads\/releases\/)(v)(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$') ]]; then

                   version=$(echo "${{ github.ref }}" | sed -n -E 's/^(refs\/heads\/releases\/)//p')
                   echo "version=$version" >> $GITHUB_OUTPUT
                   echo "type=release" >> $GITHUB_OUTPUT
                   echo "continue=true" >> $GITHUB_OUTPUT
                   echo "In \`releases/$version\` Branch, Type: \`release\`"

                 else
                   echo "Not Correct Branch. Will Not Continue"
                 fi
               else
                 echo "Not a Push Event. Will Not Continue"
               fi
             else
               echo "On a Forked Repository. Will Not Continue"
             fi

     publish_development:
       name: Publish (Development)
       environment: dockerhub-torrust
       needs: context
       if: needs.context.outputs.continue == 'true' && needs.context.outputs.type == 'development'
       runs-on: ubuntu-latest

       steps:
         - id: meta
           name: Docker Meta
           uses: docker/metadata-action@v5
           with:
             images: |
               "${{ secrets.DOCKER_HUB_USERNAME }}/${{secrets.DOCKER_HUB_REPOSITORY_NAME }}"
             tags: |
               type=ref,event=branch

         - id: login
           name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKER_HUB_USERNAME }}
             password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

         - id: setup
           name: Setup Toolchain
           uses: docker/setup-buildx-action@v3

         - name: Sign Docker Image
           uses: cosign/action-cosign@v2
           with:
             key: ${{ secrets.DOCKER_REPO_PRIVATE_KEY }}
             image: ${{ steps.meta.outputs.tags }}
             CosignArguments: sign

         - name: Build and push
           uses: docker/build-push-action@v6
           with:
             file: ./Containerfile
             push: true
             tags: ${{ steps.meta.outputs.tags }}
             labels: ${{ steps.meta.outputs.labels }}
             cache-from: type=gha
             cache-to: type=gha

     publish_release:
       name: Publish (Release)
       environment: dockerhub-torrust
       needs: context
       if: needs.context.outputs.continue == 'true' && needs.context.outputs.type == 'release'
       runs-on: ubuntu-latest

       steps:
         - id: meta
           name: Docker Meta
           uses: docker/metadata-action@v5
           with:
             images: |
               "${{ secrets.DOCKER_HUB_USERNAME }}/${{secrets.DOCKER_HUB_REPOSITORY_NAME }}"
             tags: |
               type=semver,value=${{ needs.context.outputs.version }},pattern={{raw}}
               type=semver,value=${{ needs.context.outputs.version }},pattern={{version}}
               type=semver,value=${{ needs.context.outputs.version }},pattern=v{{major}}
               type=semver,value=${{ needs.context.outputs.version }},pattern={{major}}.{{minor}}

         - id: login
           name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKER_HUB_USERNAME }}
             password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

         - id: setup
           name: Setup Toolchain
           uses: docker/setup-buildx-action@v3

         - name: Sign Docker Image
           uses: cosign/action-cosign@v2
           with:
             key: ${{ secrets.DOCKER_REPO_PRIVATE_KEY }}
             image }}>{steps.meta.outputs.tags }
             CosignArguments: sign

         - name: Build and push
           uses: docker/build-push-action@v6
           with:
             file: ./Containerfile
             push: true
             tags: ${{ steps.meta.outputs.tags }}
             labels: ${{ steps.meta.outputs.labels }}
             cache-from: type=gha
             cache-to: type=gha
   ```

   **Note:** The Cosign action is added right before the "Build and push" step in both `publish_development` and `publish_release` jobs. This ensures that images are signed before being pushed to the Docker Hub.

5. **Make Public Key Available**

   - **Store Public Key in Repository (Optional):**
     - Create a directory `.cosign` in your repository.
     - Place `cosign-key/cosign.pub` in this directory.
     - Commit and push it.

   - **Documentation:**
     - Add documentation on how users can verify the signed images.
     - Example verification command:

       ```bash
       cosign verify <image-name> --pubkey https://github.com/<your-username>/<repo>/blob/main/.cosign/cosign.pub
       ```

6. **Test the Workflow**

   - **Run CI Pipeline:**
     - Push a commit to `develop` or `main` to trigger the workflow.
     - Monitor the workflow to ensure the signing step completes successfully.

   - **Verify Signed Images:**
     - After successful publish, verify the image signatures locally using the public key.

   ```bash
   cosign verify <image-name> --pubkey .cosign/cosign.pub
   ```

7. **Inform Users About Verification**

   - **Update Documentation:**
     - Include instructions on how to verify signed images.
     - Provide the link to the public key file in the repository.

   **Example:**

   ```markdown
   ## Verify Container Image Integrity

   Our Docker images are signed using Cosign. To verify the integrity of an image:

   1. Download the public key:

      ```bash
      curl -O https://raw.githubusercontent.com/torrust/torrust-tracker/main/.cosign/cosign.pub
      ```

   2. Verify the image signature:

      ```bash
      cosign verify <image-name> --pubkey cosign.pub
      ```

   This ensures you are running an authentic and untampered image.
   ```

---
