### ISSUE TITLE
Setup tracker and seeder in local env

### ISSUE THREAD

**Issue by Almaz-KG** [torrust/torrust-tracker#150]
Hey there! 

Is there a document that describes how to set up a tracker and a local client to seed a specific file/folder? In other words, how can I configure a tracker and a seeder-client on my local machine to share a specific file?

**Comment by josecelano** [comment]
Hi @Almaz-KG no, there is not. It would be nice to add it somewhere. I'm going to describe what you have to do briefly:

### Install and run the tracker

On the docs site ([https://torrust.com/](https://torrust.com/)), you can read how to install the tracker.

1. Download

```
cd /tmp
git clone git@github.com:torrust/torrust-tracker.git
cd torrust-tracker/
```

2. Set up

Create a `config.toml` file in the root folder:

```toml
log_level = "debug"
mode = "public"
db_driver = "Sqlite3"
db_path = "./storage/database/data.db"
announce_interval = 120
min_announce_interval = 120
max_peer_timeout = 900
on_reverse_proxy = false
external_ip = "YOUR PUBLIC IP"
tracker_usage_statistics = true
persistent_torrent_completed_stat = false
inactive_peer_cleanup_interval = 600
remove_peerless_torrents = true

[[udp_trackers]]
enabled = true
bind_address = "0.0.0.0:6969"

[[http_trackers]]
enabled = false
bind_address = "0.0.0.0:7070"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api]
enabled = true
bind_address = "127.0.0.1:1212"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api.access_tokens]
admin = "MyAccessToken"
```

- Create the folder `./storage/database/`.
- Change your IP public address in the `config.toml` file `external_ip = "YOUR PUBLIC IP"`
- Remember to open port `6969` in your router.
- You do not need to expose the API publicly.

3. Run

You can run it with the following:

```s
$cargo run
...
warning: `torrust-tracker` (lib) generated 4 warnings
    Finished dev [optimized + debuginfo] target(s) in 0.09s
     Running `target/debug/torrust-tracker`
Loading configuration from config file ./config.toml
2023-01-09T12:53:39.260073070+00:00 [torrust_tracker::logging][INFO] logging initialized.
2023-01-09T12:53:39.260140809+00:00 [torrust_tracker::jobs::tracker_api][INFO] Starting Torrust API server on: http://127.0.0.1:1212
2023-01-09T12:53:39.260154466+00:00 [torrust_tracker::jobs::udp_tracker][INFO] Starting UDP server on: udp://0.0.0.0:6969
2023-01-09T12:53:39.260220576+00:00 [torrust_tracker::jobs::tracker_api][INFO] Torrust API server started
```

I'm using only the UDP tracker and the tracker API.

### Install and run the BitTorrent client

You can use any BitTorrent client. I'm going to show how to do it with BitTorrent v4.4.1.

1. You can create a new torrent (Tools->Torrent creator)

Make sure you add the tracker URLs:

![image](https://user-images.githubusercontent.com/58816/211313357-400d6593-9334-44f8-8ec2-4392dd16add3.png)

I've added two IPs for the tracker: the public IP and the localhost address.

After adding the torrent, you should see something like this:

![image](https://user-images.githubusercontent.com/58816/211313860-df461879-3e77-4dd1-9605-e0d1e959fa89.png)

Remember to open the client's port (Tools->Preferences->Connections).

![image](https://user-images.githubusercontent.com/58816/211315038-225ef32c-6db3-450c-a554-663e0fc4f8b6.png)

### Share the torrent or magnet link

You can copy the magnet link (right-click on the torrent name -> Copy -> Magnet link).

We added two IPs for the tracker:

```
magnet:?xt=urn:btih:6d8f96b4e4761a04a3193ed729ebb8993ad17f0e&xt=urn:btmh:12209c38422213e30bff212b30c360d26f9a021364228b454d58fecc4894be6d1d56&dn=mandelbrot_2048x2048.png&tr=udp%3a%2f%2f8.8.8.8%3a6969&tr=udp%3a%2f%2f127.0.0.1%3a6969
```

You can remove the localhost IP because is not reachable:

```
magnet:?xt=urn:btih:6d8f96b4e4761a04a3193ed729ebb8993ad17f0e&xt=urn:btmh:12209c38422213e30bff212b30c360d26f9a021364228b454d58fecc4894be6d1d56&dn=mandelbrot_2048x2048.png&tr=udp%3a%2f%2f8.8.8.8%3a6969
```

You can also share the torrent file.

### Getting into from the tracker

You can use the API to get info:

The list of torrents:

```s
curl http://127.0.0.1:1212/api/torrents?token=MyAccessToken  | jq
```

```json
[
  {
    "info_hash": "6d8f96b4e4761a04a3193ed729ebb8993ad17f0e",
    "seeders": 2,
    "completed": 0,
    "leechers": 0,
    "peers": null
  }
]
```

Info about a specific torrent:

```s
curl http://127.0.0.1:1212/api/torrent/6d8f96b4e4761a04a3193ed729ebb8993ad17f0e?token=MyAccessToken  | jq
```

```json
{
  "info_hash": "6d8f96b4e4761a04a3193ed729ebb8993ad17f0e",
  "seeders": 2,
  "completed": 0,
  "leechers": 0,
  "peers": [
    {
      "peer_id": {
        "id": "2d5554373434302d422864385558722943456844",
        "client": "µTorrent"
      },
      "peer_addr": "8.8.8.8:39893",
      "updated": 1673269334559,
      "updated_milliseconds_ago": 1673269334559,
      "uploaded": 0,
      "downloaded": 172204,
      "left": 0,
      "event": "None"
    },
    {
      "peer_id": {
        "id": "2d7142343431302d2a576a6c652153747851776a",
        "client": "qBittorrent"
      },
      "peer_addr": "9.9.9.9:17548",
      "updated": 1673270017001,
      "updated_milliseconds_ago": 1673270017001,
      "uploaded": 0,
      "downloaded": 0,
      "left": 0,
      "event": "None"
    }
  ]
}
```

That's all. @WarmBeer do you think that's OK? Where could we put a guide for this use case? The [docs site](https://torrust.com/)?
