### ISSUE TITLE
Package it for easy distribution

### ISSUE THREAD

**Issue by Justinzobel** [torrust/torrust-tracker#1554]
It would be great to have deb files for even easier installation on Ubuntu/Debian and other distributions.

**Comment by josecelano** [comment]
Hi @Justinzobel, I agree, I think that would be a nice thing to have. However, we are currently focused on improving the software, rather than making it easier to distribute.

On the other hand, I have no idea how to publish a Debian package.

I guess we could use a crate like this:

https://github.com/kornelski/cargo-deb

And add a new workflow like the following (or add a new job to the [deployment](https://github.com/torrust/torrust-tracker/blob/develop/.github/workflows/deployment.yaml) workflow) to release a new package when a new version is released:

```yaml
name: Release DEB Package

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build .deb package
        run: cargo deb

      - name: Upload .deb as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/debian/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I will discuss it in our next weekly meeting. Maybe we can do it before the next major release.

cc @da2ce7
