### ISSUE TITLE
Overhaul stats: Tests metrics labels with UDP server port assigned by OS

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1591]
I was wondering if the labels were assigned correctly when the UDP server port is assigned dynamically (a free port) instead of from the original configuration.

It works. This is how I tested:

1. Change the development configuration

From:

```toml
[metadata]
app = "torrust-tracker"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
threshold = "info"

[core]
inactive_peer_cleanup_interval = 120
listed = false
private = false

[core.tracker_policy]
max_peer_timeout = 60
persistent_torrent_completed_stat = true
remove_peerless_torrents = true

[[udp_trackers]]
bind_address = "0.0.0.0:6868"
tracker_usage_statistics = true

[[udp_trackers]]
bind_address = "0.0.0.0:6969"
tracker_usage_statistics = true

[[http_trackers]]
bind_address = "0.0.0.0:7070"
tracker_usage_statistics = true

[[http_trackers]]
bind_address = "0.0.0.0:7171"
tracker_usage_statistics = true

[http_api]
bind_address = "0.0.0.0:1212"

[http_api.access_tokens]
admin = "MyAccessToken"
```

To:

```toml
[metadata]
app = "torrust-tracker"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
threshold = "info"

[core]
inactive_peer_cleanup_interval = 120
listed = false
private = false

[core.tracker_policy]
max_peer_timeout = 60
persistent_torrent_completed_stat = true
remove_peerless_torrents = true

[[udp_trackers]]
bind_address = "0.0.0.0:0"
tracker_usage_statistics = true

[[udp_trackers]]
bind_address = "0.0.0.0:6969"
tracker_usage_statistics = true

[[http_trackers]]
bind_address = "0.0.0.0:7070"
tracker_usage_statistics = true

[[http_trackers]]
bind_address = "0.0.0.0:7171"
tracker_usage_statistics = true

[http_api]
bind_address = "0.0.0.0:1212"

[http_api.access_tokens]
admin = "MyAccessToken"
```

Notice port `6868` has been changed to `0`.

2. Run tracker with `cargo run`

You should see the assigned port on the output:

```output
2025-06-18T15:13:16.326628Z  INFO run_with_graceful_shutdown{cookie_lifetime=120s}: UDP TRACKER: Starting on: 0.0.0.0:0
2025-06-18T15:13:16.326673Z  INFO run_with_graceful_shutdown{cookie_lifetime=120s}: UDP TRACKER: Started on: udp://0.0.0.0:55696
2025-06-18T15:13:16.326695Z  INFO start:start_job:start{cookie_lifetime=120s}: torrust_udp_tracker_server::server::states: return=Running (with local address): 0.0.0.0:55696
2025-06-18T15:13:16.326734Z  INFO run_with_graceful_shutdown{cookie_lifetime=120s}: UDP TRACKER: Starting on: 0.0.0.0:6969
2025-06-18T15:13:16.326765Z  INFO run_with_graceful_shutdown{cookie_lifetime=120s}: UDP TRACKER: Started on: udp://0.0.0.0:6969
```

4. Run the tracker client
```console
cargo run -p torrust-tracker-client --bin udp_tracker_client announce udp://127.0.0.1:55696 000620bbc6c52d5a96d98f6c0f1dfa523a40df82 | jq
```

5. Verify the label is correct in prometheous export

Load the URL http://localhost:1212/api/v1/metrics?token=MyAccessToken&format=prometheus

```
# HELP udp_tracker_core_requests_received_total Total number of UDP requests received
# TYPE udp_tracker_core_requests_received_total counter
udp_tracker_core_requests_received_total{request_kind="connect",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 1
udp_tracker_core_requests_received_total{request_kind="connect",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 1
udp_tracker_core_requests_received_total{request_kind="announce",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 1
udp_tracker_core_requests_received_total{request_kind="announce",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 1

# HELP swarm_coordination_registry_torrents_added_total The total number of torrents added.
# TYPE swarm_coordination_registry_torrents_added_total counter
swarm_coordination_registry_torrents_added_total 1

# HELP udp_tracker_server_requests_received_total Total number of UDP requests received
# TYPE udp_tracker_server_requests_received_total counter
udp_tracker_server_requests_received_total{server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 2
udp_tracker_server_requests_received_total{server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 2

# HELP udp_tracker_server_responses_sent_total Total number of UDP responses sent
# TYPE udp_tracker_server_responses_sent_total counter
udp_tracker_server_responses_sent_total{request_kind="announce",result="ok",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 1
udp_tracker_server_responses_sent_total{request_kind="announce",result="ok",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 1
udp_tracker_server_responses_sent_total{request_kind="connect",result="ok",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 1
udp_tracker_server_responses_sent_total{request_kind="connect",result="ok",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 1

# HELP udp_tracker_server_requests_accepted_total Total number of UDP requests accepted
# TYPE udp_tracker_server_requests_accepted_total counter
udp_tracker_server_requests_accepted_total{request_kind="announce",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 1
udp_tracker_server_requests_accepted_total{request_kind="connect",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 1
udp_tracker_server_requests_accepted_total{request_kind="connect",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 1
udp_tracker_server_requests_accepted_total{request_kind="announce",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 1

# HELP swarm_coordination_registry_peers_added_total The total number of peers added.
# TYPE swarm_coordination_registry_peers_added_total counter
swarm_coordination_registry_peers_added_total{peer_role="seeder"} 2

# HELP tracker_core_persistent_torrents_downloads_total The total number of torrent downloads (persisted).
# TYPE tracker_core_persistent_torrents_downloads_total counter
tracker_core_persistent_torrents_downloads_total 5

# HELP swarm_coordination_registry_peers_inactive_total The total number of inactive peers.
# TYPE swarm_coordination_registry_peers_inactive_total gauge
swarm_coordination_registry_peers_inactive_total 0

# HELP swarm_coordination_registry_peer_connections_total The total number of peer connections (one connection per torrent).
# TYPE swarm_coordination_registry_peer_connections_total gauge
swarm_coordination_registry_peer_connections_total{peer_role="seeder"} 2

# HELP udp_tracker_server_performance_avg_processing_time_ns Average time to process a UDP request in nanoseconds
# TYPE udp_tracker_server_performance_avg_processing_time_ns gauge
udp_tracker_server_performance_avg_processing_time_ns{request_kind="announce",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 89873.5
udp_tracker_server_performance_avg_processing_time_ns{request_kind="connect",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 51116
udp_tracker_server_performance_avg_processing_time_ns{request_kind="announce",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="6969",server_binding_protocol="udp"} 141976
udp_tracker_server_performance_avg_processing_time_ns{request_kind="connect",server_binding_address_ip_family="inet",server_binding_address_ip_type="plain",server_binding_ip="0.0.0.0",server_binding_port="55696",server_binding_protocol="udp"} 48085.5

# HELP swarm_coordination_registry_torrents_total The total number of torrents.
# TYPE swarm_coordination_registry_torrents_total gauge
swarm_coordination_registry_torrents_total 1

# HELP swarm_coordination_registry_torrents_inactive_total The total number of inactive torrents.
# TYPE swarm_coordination_registry_torrents_inactive_total gauge
swarm_coordination_registry_torrents_inactive_total 0
```
