### ISSUE TITLE
Tracker API enabled in default configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#590]
When I implemented the Health Check API I accidentally enabled the tracker API for the development container configuration in this commit e1a45a2.

This line: https://github.com/torrust/torrust-tracker/blob/develop/share/default/config/tracker.development.sqlite3.toml#L28

It's also enabled in the other container configurations. If I'm not wrong initially all services were disabled so the admin has to enable them explicitly.

Should we disable the API by default in all configurations?

**Comment by cgbosse** [comment]
@WarmBeer and @da2ce7 what do you have to add?

**Comment by josecelano** [comment]
Hi @da2ce7 @WarmBeer I think the default configuration could be:

- All services enabled.
- All services running on localhost.

This way you have to manually change the interface if you want to expose the service. For development and testing would be a better option.

```toml
announce_interval = 120
db_driver = "Sqlite3"
db_path = "./storage/tracker/lib/database/sqlite3.db"
external_ip = "0.0.0.0"
inactive_peer_cleanup_interval = 600
log_level = "info"
max_peer_timeout = 900
min_announce_interval = 120
mode = "public"
on_reverse_proxy = false
persistent_torrent_completed_stat = false
remove_peerless_torrents = true
tracker_usage_statistics = true

[[udp_trackers]]
bind_address = "127.0.0.1:6969"
enabled = true

[[http_trackers]]
bind_address = "127.0.0.1:7070"
enabled = true
ssl_cert_path = ""
ssl_enabled = false
ssl_key_path = ""

[http_api]
bind_address = "127.0.0.1:1212"
enabled = true
ssl_cert_path = ""
ssl_enabled = false
ssl_key_path = ""

[http_api.access_tokens]
admin = "MyAccessToken"

[health_check_api]
bind_address = "127.0.0.1:1313"

```
