### ISSUE TITLE
Config overhaul: split tracker mode

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#932]
Parent issue: https://github.com/torrust/torrust-tracker/issues/401
Relates to: https://github.com/torrust/torrust-tracker/issues/401#issuecomment-2182206838

Tracker privacy (public and private) and torrent restrictions (whitelisted or not) are totally independent options.

### Current

```rust
pub enum TrackerMode {
    Public,
    Listed,
    Private,
    PrivateListed,
}
```

```toml
[core]
mode = "public"
```

### New Version

```toml
[core]
private = true # boolean
listed = true # boolean
```
