### ISSUE TITLE
Overhaul tracker keys: option to disable auth key expiration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#978]
Parent issue: https://github.com/torrust/torrust-tracker/issues/773

### Discussed in https://github.com/torrust/torrust-tracker/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **rakema01** May 23, 2022</sup>
Would be a neat thing to have when the focus of the site is to seed for long periods of time. Also especially helpful when you've got too many torrents and having to change the tracker URL to match the key is a pain. Of course, there's the option to change the expiry length to a random huge number but having an option to outright disable expiry checks is a bit cleaner in my opinion. In its place, we could have an option for the key be manually regenerated when needed.</div>

I think we could add a config option like this:

```toml
[core]
private = true
check_keys_expiration = true     # The new option. It only makes sense when `private = true`
tracker_usage_statistics = true
```

When `check_keys_expiration = false` we don't call `auth::verify(key)` in this function:

```rust
pub async fn verify_auth_key(&self, key: &Key) -> Result<(), auth::Error> {
    // code-review: this function is public only because it's used in a test.
    // We should change the test and make it private.
    match self.keys.read().await.get(key) {
        None => Err(auth::Error::UnableToReadKey {
            location: Location::caller(),
            key: Box::new(key.clone()),
        }),
        Some(key) => auth::verify(key),
    }
}
```

cc @da2ce7

**Comment by josecelano** [comment]
We've just had a discussion and agreed on adding a new section for configuration related to `private` mode:

```toml
[core]
private = true

[core.private]
check_keys_expiration = true
```

If the tracker is not private (`private = false`) and the section is present the application should throw a configuration error. For example:

```toml
[core]
private = false

[core.private]
```

Even if the section is empty. The error should indicate the user has to enable the private mode.

cc @da2ce7

**Comment by josecelano** [comment]
> ```toml
> [core]
> private = true
> 
> [core.private]
> check_keys_expiration = true
> ```

I can't use the name `[core.private]`. I will use: `[core.private_mode]`

```toml
[core]
private = false

[core.private_mode]
check_keys_expiration = true
```
